import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Indian-inspired color palette
        saffron: {
          50: "#fff8e6",
          100: "#ffefc4",
          200: "#ffe29d",
          300: "#ffd575",
          400: "#ffc94e",
          500: "#ffbc26",
          600: "#e6a922",
          700: "#b3841a",
          800: "#805e13",
          900: "#4d380b",
        },
        spice: {
          50: "#fdf2f2",
          100: "#fce4e4",
          200: "#f9c9c9",
          300: "#f5adad",
          400: "#f28585",
          500: "#ee5d5d",
          600: "#d65454",
          700: "#a74141",
          800: "#782f2f",
          900: "#491c1c",
        },
        turmeric: {
          50: "#fffbeb",
          100: "#fef3c7",
          200: "#fde68a",
          300: "#fcd34d",
          400: "#fbbf24",
          500: "#f59e0b",
          600: "#d97706",
          700: "#b45309",
          800: "#92400e",
          900: "#78350f",
        },
        neem: {
          50: "#f0fdf4",
          100: "#dcfce7",
          200: "#bbf7d0",
          300: "#86efac",
          400: "#4ade80",
          500: "#22c55e",
          600: "#16a34a",
          700: "#15803d",
          800: "#166534",
          900: "#14532d",
        },
        peacock: {
          50: "#edfcfd",
          100: "#d2f5f9",
          200: "#a8eaf2",
          300: "#70d7e5",
          400: "#2cbbd1",
          500: "#1a9db1",
          600: "#167d94",
          700: "#166678",
          800: "#175363",
          900: "#184654",
        },
        // New expanded color system inspired by India's palate
        haldi: {
          50: "#fffaeb",
          100: "#fef0c7",
          200: "#fde28a",
          300: "#fbd44d",
          400: "#f9c22e",
          500: "#F4C430", // Haldi Yellow
          600: "#d9a118",
          700: "#b37d13",
          800: "#8c5e14",
          900: "#734d15",
        },
        curryleaf: {
          50: "#f0f9f1",
          100: "#dcf1df",
          200: "#bbe3c2",
          300: "#8ecf9a",
          400: "#5fb46e",
          500: "#2E7D32", // Curry Leaf Green
          600: "#236528",
          700: "#1d5021",
          800: "#1a401d",
          900: "#15351a",
        },
        tandoori: {
          50: "#fef2f2",
          100: "#fee2e2",
          200: "#fecaca",
          300: "#fca5a5",
          400: "#f87171",
          500: "#ef4444",
          600: "#dc2626",
          700: "#B71C1C", // Tandoori Red
          800: "#991b1b",
          900: "#7f1d1d",
        },
        indigo: {
          50: "#eef2ff",
          100: "#e0e7ff",
          200: "#c7d2fe",
          300: "#a5b4fc",
          400: "#818cf8",
          500: "#6366f1",
          600: "#4f46e5",
          700: "#4338ca",
          800: "#3730a3",
          900: "#26418F", // Indigo (Natural Dye)
        },
        mustard: {
          50: "#fdfaed",
          100: "#f9f1d1",
          200: "#f2e2a6",
          300: "#e9cd70",
          400: "#dfb446",
          500: "#d19d2a",
          600: "#A97444", // Mustard Brown
          700: "#8c5e2f",
          800: "#734c2c",
          900: "#5f3f28",
        },
        sweetlime: {
          50: "#FFF3D9", // Sweet Lime Cream
          100: "#ffefc4",
          200: "#ffe29d",
          300: "#ffd575",
          400: "#ffc94e",
          500: "#ffbc26",
          600: "#e6a922",
          700: "#b3841a",
          800: "#805e13",
          900: "#4d380b",
        },
        jaggery: {
          50: "#fbf8f1",
          100: "#f5eddc",
          200: "#ead8b9",
          300: "#dbbe8c",
          400: "#cca366",
          500: "#b78b4b",
          600: "#996515", // Jaggery Bronze
          700: "#7c5019",
          800: "#66421a",
          900: "#553819",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "cooking-stir": {
          "0%, 100%": { transform: "rotate(-5deg)" },
          "50%": { transform: "rotate(5deg)" },
        },
        "cooking-boil": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        },
        "cooking-chop": {
          "0%, 100%": { transform: "translateX(0)" },
          "50%": { transform: "translateX(5px)" },
        },
        "spice-sprinkle": {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "50%": { opacity: "1" },
          "100%": { opacity: "0", transform: "translateY(10px)" },
        },
        "flame-flicker": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.8", transform: "scale(0.95)" },
        },
        "mandala-unfold": {
          "0%": { transform: "scale(0) rotate(0deg)", opacity: "0" },
          "50%": { opacity: "1" },
          "100%": { transform: "scale(1) rotate(360deg)", opacity: "1" },
        },
        "kolam-draw": {
          "0%": { strokeDashoffset: "1000" },
          "100%": { strokeDashoffset: "0" },
        },
        "rangoli-appear": {
          "0%": { opacity: "0", transform: "scale(0.8)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "leaf-sway": {
          "0%, 100%": { transform: "rotate(-2deg)" },
          "50%": { transform: "rotate(2deg)" },
        },
        "thali-rotate": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "diya-flicker": {
          "0%, 100%": { opacity: "1", filter: "brightness(1)" },
          "50%": { opacity: "0.8", filter: "brightness(1.2)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "cooking-stir": "cooking-stir 2s ease-in-out infinite",
        "cooking-boil": "cooking-boil 1.5s ease-in-out infinite",
        "cooking-chop": "cooking-chop 0.5s ease-in-out infinite",
        "spice-sprinkle": "spice-sprinkle 2s ease-in-out infinite",
        "flame-flicker": "flame-flicker 1.5s ease-in-out infinite",
        "mandala-unfold": "mandala-unfold 2s ease-out",
        "kolam-draw": "kolam-draw 3s ease-in-out forwards",
        "rangoli-appear": "rangoli-appear 0.5s ease-out",
        "leaf-sway": "leaf-sway 3s ease-in-out infinite",
        "thali-rotate": "thali-rotate 30s linear infinite",
        "diya-flicker": "diya-flicker 2s ease-in-out infinite",
      },
      backgroundImage: {
        "pattern-madhubani": "url('/patterns/madhubani-pattern.svg')",
        "pattern-warli": "url('/patterns/warli-pattern.svg')",
        "pattern-kalamkari": "url('/patterns/kalamkari-pattern.svg')",
        "pattern-phulkari": "url('/patterns/phulkari-pattern.svg')",
        "pattern-kolam": "url('/patterns/kolam-pattern.svg')",
        "texture-banana-leaf": "url('/textures/banana-leaf.svg')",
        "texture-spice-grain": "url('/textures/spice-grain.svg')",
        "texture-mud-wall": "url('/textures/mud-wall.svg')",
        "texture-haldi-wash": "url('/textures/haldi-wash.svg')",
        "gradient-pongal": "linear-gradient(135deg, #FFF3D9 0%, #F4C430 100%)",
        "gradient-onam": "linear-gradient(135deg, #dcfce7 0%, #2E7D32 100%)",
        "gradient-diwali": "linear-gradient(135deg, #fef0c7 0%, #F4C430 100%)",
        "gradient-holi": "linear-gradient(135deg, #e0e7ff 0%, #26418F 100%)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
